// Common disposable / temporary email domains. Checked both client-side
// (instant feedback) and server-side (cannot be bypassed).
// Add new domains at the bottom of the set as they're discovered.

export const DISPOSABLE_DOMAINS = new Set([
  // --- High-volume disposable services ---
  'mailinator.com', 'guerrillamail.com', 'guerrillamail.org', 'guerrillamail.net',
  'guerrillamail.biz', 'guerrillamail.de', 'guerrillamail.info', 'guerrillamailblock.com',
  'grr.la', 'sharklasers.com', 'spam4.me', 'yopmail.com', 'yopmail.fr',
  'cool.fr.nf', 'jetable.fr.nf', 'nospam.ze.tc', 'nomail.xl.cx',
  'mega.zik.dj', 'speed.1s.fr', 'courriel.fr.nf', 'moncourrier.fr.nf',
  'monemail.fr.nf', 'monmail.fr.nf',
  'tempmail.com', 'tempmail.net', 'tempmail.org', 'temp-mail.org',
  'temp-mail.io', 'tempr.email', 'tempinbox.com', 'tempinbox.co.uk',
  '10minutemail.com', '10minutemail.net', '10minutemail.org', '10minutemail.co.za',
  '10minutemail.de', '10minutemail.ru', '10minutemail.be', '10minutemail.us',
  'trashmail.com', 'trashmail.me', 'trashmail.at', 'trashmail.io',
  'trashmail.net', 'trashmail.org', 'trashmail.xyz',
  'dispostable.com', 'discard.email', 'mailnull.com',
  'spamgourmet.com', 'spamgourmet.net', 'spamgourmet.org',
  'spambox.us', 'spambox.info', 'spam.la',
  'maildrop.cc', 'mailnesia.com', 'mailexpire.com',
  'fakeinbox.com', 'fakeinbox.net', 'getairmail.com',
  'throwam.com', 'throwam.us',
  'wegwerfmail.de', 'wegwerfmail.net', 'wegwerfmail.org',
  'mailme.lv', 'mailin8r.com', 'mailme24.com',
  'mailmoat.com', 'mailscrap.com', 'mailseal.de',
  'mailshell.com', 'mailslite.com', 'mailtome.de',
  'mailzilla.com', 'mailzilla.org',
  'mt2009.com', 'mt2014.com', 'mt2015.com',
  'mytempemail.com', 'mytrashmail.com',
  'noclickemail.com', 'noblepioneer.com',
  'nomail2me.com', 'nospam.ze.tc',
  'objectmail.com', 'odaymail.com',
  'oneoffemail.com', 'onewaymail.com',
  'ownmail.net', 'ownsmail.com',
  'pookmail.com', 'privacy.net',
  'quickinbox.com', 'rcpt.at',
  'rklips.com', 'rppkn.com',
  'rtrtr.com', 'safetymail.info',
  'safetypost.de', 'sandelf.de',
  'send22u.info', 'sendspamhere.com',
  'shieldedmail.com', 'shiftmail.com',
  'shit.dns-cloud.net', 'shitmail.me',
  'shitmail.org', 'shitware.nl',
  'shortmail.net', 'sibmail.com',
  'skeefmail.com', 'slopsbox.com',
  'smellfear.com', 'snakemail.com',
  'sneakemail.com', 'sneakmail.de',
  'snkmail.com', 'sofimail.com',
  'sofort-mail.de', 'sogetthis.com',
  'soodonims.com', 'spam.care',
  'spam.su', 'spamavert.com',
  'spambob.com', 'spambob.net',
  'spambob.org', 'spambog.com',
  'spambog.de', 'spambog.ru',
  'spamcorpse.com', 'spamed.com',
  'spamex.com', 'spamfree.eu',
  'spamfree24.de', 'spamfree24.eu',
  'spamfree24.info', 'spamfree24.net',
  'spamfree24.org', 'spamgoes.in',
  'spamherelots.com', 'spamhereplease.com',
  'spamhole.com', 'spamify.com',
  'spaminator.de', 'spamkill.info',
  'spaml.com', 'spaml.de',
  'spamoff.de', 'spamslicer.com',
  'spamspot.com', 'spamstack.net',
  'spamthis.co.uk', 'spamthisplease.com',
  'spamtrail.com', 'spamtroll.net',
  'speed.1s.fr', 'supergreatmail.com',
  'supermailer.jp', 'suremail.info',
  'svkmail.com', 'sweetxxx.de',
  'tafmail.com', 'tagyourself.com',
  'teleworm.com', 'teleworm.us',
  'tempalias.com', 'tempe-mail.com',
  'tempemail.biz', 'tempemail.co.za',
  'tempemail.com', 'tempemail.net',
  'tempemailaddress.com', 'tempinbox.com',
  'temporarioemail.com.br', 'temporaryemail.net',
  'temporaryemail.us', 'temporaryforwarding.com',
  'temporaryinbox.com', 'temporarymailaddress.com',
  'thankyou2010.com', 'thc.st',
  'throwam.com', 'throwandsend.com',
  'throwawayemailaddress.com', 'throwam.com',
  'tilien.com', 'tittbit.in',
  'tizi.com', 'tmp.com.br',
  'tmailinator.com', 'toiea.com',
  'topranklist.de', 'tradermail.info',
  'trash-mail.at', 'trash-mail.com',
  'trash-mail.de', 'trash-mail.ga',
  'trash-mail.io', 'trash-mail.ml',
  'trashemail.de', 'trashimail.de',
  'trashmailer.com', 'trashmail.app',
  'trashmail.at', 'trashmail.com',
  'trashmail.fr', 'trashmail.fu.cx',
  'trashmail.gq', 'trashmail.io',
  'trashmail.me', 'trashmail.ml',
  'trashmail.net', 'trashmail.org',
  'trashmail.se', 'trashmail.tk',
  'trashmail.ws', 'trashmailer.com',
  'trbvm.com', 'trialmail.de',
  'trommlerklause.de', 'turual.com',
  'twinmail.de', 'tyldd.com',
  'uggsrock.com', 'umail.net',
  'upliftnow.com', 'uplipht.com',
  'uroid.com', 'us.af',
  'venompen.com', 'veryrealemail.com',
  'vidchart.com', 'viditag.com',
  'viewcastmedia.com', 'viewcastmedia.net',
  'viewcastmedia.org', 'vikingsonly.com',
  'vomoto.com', 'vpn.st',
  'vsimcard.com', 'vubby.com',
  'wasteland.raptors.dk', 'watch-harry-potter.com',
  'webemail.me', 'webm4il.info',
  'weg-werf-email.de', 'wegwerf-email.at',
  'wegwerf-email.de', 'wegwerf-email.net',
  'wegwerf-email.org', 'wegwerfadresse.de',
  'wegwerfemail.com', 'wegwerfemail.de',
  'wegwerfemail.info', 'wegwerfemail.net',
  'wegwerfemail.org', 'wegwerfmail.de',
  'wegwerfmail.info', 'wegwerfmail.net',
  'wegwerfmail.org',
  // --- Catch-all patterns we also reject ---
  'mailnull.com', 'spamgourmet.com',
  // --- Additional common ones ---
  'throwaway.email', 'throwam.com',
  'inboxbear.com', 'burnthespam.info',
  'deadaddress.com', 'despam.it',
  'devnullmail.com', 'dfgh.net',
  'digitalsanctuary.com', 'discardmail.com',
  'discardmail.de', 'disposableaddress.com',
  'disposableemailaddresses.com', 'disposableinbox.com',
  'dispostable.com', 'dodgit.com',
  'dodgit.org', 'donemail.ru',
  'dontsendmespam.de', 'drdrb.com',
  'drdrb.net', 'dropmail.me',
  'duam.net', 'dudmail.com',
  'dump-email.info', 'dumpandfuck.com',
  'dumpmail.de', 'dumpyemail.com',
  'e4ward.com', 'easytrashmail.com',
  'einrot.com', 'einrot.de',
  'eintagsmail.de', 'email60.com',
  'emailgo.de', 'emailias.com',
  'emailinfive.com', 'emailisvalid.com',
  'emailmiser.com', 'emailsensei.com',
  'emailtemporario.com.br', 'emailto.de',
  'emailwarden.com', 'emailx.at.hm',
  'emailxfer.com', 'emkei.cz',
  'emkei.ga', 'emkei.gq',
  'emkei.ml', 'emkei.tk',
  'emz.net', 'enterto.com',
  'ephemail.net', 'etranquil.com',
  'etranquil.net', 'etranquil.org',
  'explodemail.com', 'express.net.ua',
  'extremail.ru', 'eyepaste.com',
  'fakeinbox.com', 'fakeinbox.info',
  'fakeinbox.net', 'fakeinbox.org',
  'fakemailgenerator.com', 'fakemail.fr',
  'fakemailz.com', 'fammix.com',
  'fansworldwide.de', 'fantasymail.de',
  'fastacura.com', 'fastchevy.com',
  'fastchrysler.com', 'fastkawasaki.com',
  'fastmazda.com', 'fastmitsubishi.com',
  'fastnissan.com', 'fastsubaru.com',
  'fastsuzuki.com', 'fasttoyota.com',
  'fastyamaha.com', 'fatflap.com',
  'fdcserver.net', 'fddns.ml',
  'fepg.net', 'fightallspam.com',
  'filzmail.com', 'fivemail.de',
  'fizmail.com', 'fleckens.hu',
  'flerverber.com',
  // catch-all
  'getnada.com', 'getonemail.com',
  'getonemail.net', 'giantmail.de',
  'girlsunder.com', 'globaltouron.com',
  'grandmamail.com', 'grandmasmail.com',
  'great-host.in', 'greensloth.com',
  'grr.la', 'gsrv.co.uk',
  'gustr.com',
  'h8s.org', 'hailmail.net',
  'hat-geld.de', 'hatespam.org',
  'herp.in', 'hidemail.de',
  'hidzz.com', 'hmamail.com',
  'hopemail.biz', 'hostermail.com',
  'hostmaster.in', 'hot-mail.xyz',
  'hotpop.com', 'ieatspam.eu',
  'ieatspam.info', 'ieh-mail.de',
  'igelonline.de', 'imails.info',
  'inboxclean.com', 'inboxclean.org',
  'inboxstore.me', 'incognitomail.com',
  'incognitomail.net', 'incognitomail.org',
  'ineec.net', 'inoutmail.de',
  'inoutmail.eu', 'inoutmail.info',
  'inoutmail.net',
])

// Additional well-known services not covered by domain list
const EXTRA_DISPOSABLE = new Set([
  'mailsac.com', 'mohmal.com', 'harakirimail.com', 'emailondeck.com',
  'inboxkitten.com', 'rhyta.com', 'anonymousemail.me', 'byom.de',
  'cuvox.de', 'dayrep.com', 'eelmail.com', 'flurred.com',
  'haltospam.com', 'meinspamschutz.de', 'mox.pp.ua', 'plexolan.de',
  'proxymail.eu', 'teewars.org', 'zoemail.net', 'ufacoder.com',
  'daxmail.net', 'nwldx.com', 'kzccv.com', 'lhsdv.com',
  'qisdo.com', 'qisoa.com', 'rvb.ro', 's0ny.net',
  'pjjkp.com', 'virtbox.com', 'objectmail.com',
])

// If the domain contains any of these keywords it is almost certainly disposable.
// This catches new services without requiring list updates.
const SUSPICIOUS_PATTERNS = [
  'tempmail', 'throwaway', 'disposable', 'trashmail', 'spammail',
  'fakeinbox', 'burnermail', 'anonymousmail', '10minute', 'minutemail',
  'guerrilla', 'mailinator', 'yopmail', 'discard', 'dropmail',
]

export function isDisposableEmail(email: string): boolean {
  const domain = email.trim().toLowerCase().split('@')[1]
  if (!domain) return false
  if (DISPOSABLE_DOMAINS.has(domain)) return true
  if (EXTRA_DISPOSABLE.has(domain)) return true
  return SUSPICIOUS_PATTERNS.some((p) => domain.includes(p))
}
